### ISSUE TITLE
DHE-Modules

### ISSUE THREAD

**Issue by dhemery** [VCVRack/library#485]
Please update DHE-Modules to v0.6.1.

latestVersion: 0.6.1
Tag: v0.6.1
Commit: a42343130322e652bd3f356287afd24ba534a652

All other manifest details remain the same as v0.6.0.

**Comment by dhemery** [comment]
Urgh! Hold off, please. I have to correct a switch label.

**Comment by dhemery** [comment]
Okay, I've corrected the error and edited the the issue description to point to the now correct commit.

I apologize for the inconvenience.

Please review and update DHE-Modules.

**Comment by AndrewBelt** [comment]
Updated build

**Comment by AndrewBelt** [comment]
Updated build

**Comment by dhemery** [comment]
Please update DHE-Modules to v0.6.3.

latestVersion: 0.6.3
Tag: v0.6.3
Commit: dedce8b31f09d49171a27f8aeb0964ba7064ead9

All other manifest details remain the same as v0.6.2.

**Comment by cschol** [comment]
Build updated.

**Comment by AndrewBelt** [comment]
Build error on Linux.
```cpp
g++  -Wsuggest-override -std=c++11 -I./plugin/include -DSLUG=DHE-Modules -fPIC -I/Rack-SDK/include -I/Rack-SDK/dep/include -DVERSION=0.6.4 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -c -o build/plugin/src/cubic.cpp.o plugin/src/cubic.cpp
plugin/src/func.cpp: In instantiation of 'DHE::MultiplicationRangeSwitch<P>::MultiplicationRangeSwitch() [with P = DHE::FuncPanel]':
/Rack-SDK/include/app.hpp:222:16:   required from 'static T* rack::Component::create(rack::Vec, rack::Module*) [with T = DHE::MultiplicationRangeSwitch<DHE::FuncPanel>]'
/Rack-SDK/include/app.hpp:255:30:   required from 'static T* rack::ParamWidget::create(rack::Vec, rack::Module*, int, float, float, float) [with T = DHE::MultiplicationRangeSwitch<DHE::FuncPanel>]'
./plugin/include/display/panel.h:141:37:   required from 'T* DHE::Panel<P>::param(int, float, float, const std::function<void(float)>&) const [with T = DHE::MultiplicationRangeSwitch<DHE::FuncPanel>; P = DHE::FuncPanel]'
./plugin/include/display/panel.h:116:23:   required from 'C<P>* DHE::Panel<P>::toggle(int, int, const std::function<void(int)>&) const [with C = DHE::MultiplicationRangeSwitch; P = DHE::FuncPanel]'
plugin/src/func.cpp:161:76:   required from here
plugin/src/func.cpp:119:60: error: call of overloaded 'Toggle(<brace-enclosed initializer list>)' is ambiguous
   MultiplicationRangeSwitch() : Toggle<P, 4>{"counter-mult"} {}
```
Why do you need an initializer list here? Your `Toggle` constructor just needs a `std::string`. Why not just parens?

**Comment by dhemery** [comment]
Braced initialization is a semi-popular style choice, encouraged by the developers of C++. See item ES.23 of ISO C++ Core Guidelines: https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines???#Res-list.

Of course, your compiler trumps my style choices, so I’ll fix this.

What version of gcc to you use for official builds? I will arrange to use that version for my own linux builds, so that in the future I can detect compilation problems myself before I submit updates.

**Comment by AndrewBelt** [comment]
Ha yeah, style recommendations from language standard committees are the worst. The ISO guidelines, Stroustrup's old style guide, Python PEP 8, etc. If you follow the exact opposite of what they say, you usually end up writing more readable, managable code IMO.

**Comment by dhemery** [comment]
I really do want to know what version of gcc you use to build the official plugins Linux, so I can find and fix stuff like this on my own.

**Comment by AndrewBelt** [comment]
Whatever is default on Ubuntu 16.04. I could log into the docker shell if you really need me to.

**Comment by dhemery** [comment]
No need. I have been testing on a computer with Ubuntu 18.04 installed, and that's why I missed this error. If I use 16.04, the default gcc (5.5.0) gives the same error. I'll have to switch my Linux dev computer to 16.0.4.

Thanks for the info.

**Comment by dhemery** [comment]
Constructor call ambiguity has been resolved (in gcc 5.5.0).

Please update DHE-Modules to v0.6.4.

latestVersion: 0.6.4
commit: bc8ff608d462ea64cbcc82df5fe73ace486094bf

All other manifest details remain the same as v0.6.3.

**Comment by AndrewBelt** [comment]
Build updated.

**Comment by dhemery** [comment]
Please update DHE-Modules to v0.6.5.

latestVersion: 0.6.5
Tag: v0.6.5
Commit: 6261dfaeaa4e9abb589f10e4178930140425bea2

All other manifest details remain the same as v0.6.4.

**Comment by AndrewBelt** [comment]
Updated build

**Comment by dhemery** [comment]
Please update DHE-Modules
Version: 1.0.0
Commit: bb67375a37bd2ec35f82170cbd2e03c4df53930f

**Comment by cschol** [comment]
@dhemery Version 1.0.0 of the plugin does not compile on **GNU/Linux (Ubuntu 18.04, g++ 7.4.0)** and **Windows (x86_64-w64-mingw32-g++ 7.3-posix 20180312)** fails.

```
In file included from src/modules/Swave.cpp:1:0:
./include/modules/Swave.h:20:8: error: ‘unique_ptr’ in namespace ‘std’ does not name a template type
   std::unique_ptr<CurvatureControl> shape;
        ^~~~~~~~~~
src/modules/Swave.cpp: In constructor ‘DHE::Swave::Swave()’:
src/modules/Swave.cpp:15:3: error: ‘shape’ was not declared in this scope
   shape = std::unique_ptr<CurvatureControl>(new CurvatureControl(
   ^~~~~
src/modules/Swave.cpp:15:3: note: suggested alternative: ‘scale’
   shape = std::unique_ptr<CurvatureControl>(new CurvatureControl(
   ^~~~~
   scale
src/modules/Swave.cpp:15:16: error: ‘unique_ptr’ is not a member of ‘std’
   shape = std::unique_ptr<CurvatureControl>(new CurvatureControl(
                ^~~~~~~~~~
src/modules/Swave.cpp:15:16: note: suggested alternative: ‘unique_copy’
   shape = std::unique_ptr<CurvatureControl>(new CurvatureControl(
                ^~~~~~~~~~
                unique_copy
src/modules/Swave.cpp:15:43: error: expected primary-expression before ‘>’ token
   shape = std::unique_ptr<CurvatureControl>(new CurvatureControl(
                                           ^
src/modules/Swave.cpp: In member function ‘virtual void DHE::Swave::process(const rack::engine::Module::ProcessArgs&)’:
src/modules/Swave.cpp:21:23: error: ‘shape’ was not declared in this scope
   auto const shaped = shape->taper(normalized);
                       ^~~~~
src/modules/Swave.cpp:21:23: note: suggested alternative: ‘shaped’
   auto const shaped = shape->taper(normalized);
                       ^~~~~
                       shaped
/home/cschol/src/Rack-1.0/compile.mk:61: recipe for target 'build/src/modules/Swave.cpp.o' failed
make: *** [build/src/modules/Swave.cpp.o] Error 1
```

I think you are missing an `#include <memory>`.

**Mac** compilation works without error.

**Comment by dhemery** [comment]
Fixed
Version: 1.0.0
Commit: 622f1b6ce486174f5da7a171808227702d44380c

**Comment by cschol** [comment]
`plugin.json` requires update: https://github.com/dhemery/DHE-Modules/issues/16

**Comment by dhemery** [comment]
Fixed
Version: 1.0.0
Commit: 91d661bcba85a2cb59278477c92ca85e4c32785f

**Comment by dhemery** [comment]
Removed erroneous colon from plugin.json slug keys.
Version: 1.0.0
Commit: ac2181f36080a2d5fb87664764dd1881fa3d5fd7

**Comment by cschol** [comment]
Slug update required: https://github.com/dhemery/DHE-Modules/issues/19

**Comment by dhemery** [comment]
I don't understand. In the commit I sent you (ac2181f36080a2d5fb87664764dd1881fa3d5fd7), the slug is correct:
https://github.com/dhemery/DHE-Modules/blob/ac2181f36080a2d5fb87664764dd1881fa3d5fd7/plugin.json#L40

Are you building against some other commit? If so, which one? And why?

**Comment by cschol** [comment]
That's the version I use. The `plugin.json` is correct, but:

```
p->addModel(rack::createModel<DHE::Func6, DHE::Func6Panel>("Func 6"));
```

in `dhe-modules.cpp` is not correct and contains the whitespace still.

**Comment by dhemery** [comment]
Ah. Got it. Yeah, I’ll fix that right away.

**Comment by dhemery** [comment]
Removed extraneous space from slug in dhe-modules.cpp
Version: 1.0.0
Commit: fb5b50a84b812ec64e967d4ff157ff0458181ddd

**Comment by cschol** [comment]
Port methods need update: https://github.com/dhemery/DHE-Modules/issues/20

**Comment by dhemery** [comment]
Updated uses of `.active` to call `isConnected()`

Version: 1.0.0
Commit:: 4191de3907a997ac3cdf0367759017b8175af692

**Comment by dhemery** [comment]
Please update DHE-Modules to v1.0.1

Commit: b0989fca6d4891aa5858f0d5a981529f281998f0

**Comment by dhemery** [comment]
Please update DHE-Modules to v1.0.2
Commit: f28308ba2f346ee62f468dc7ba91295ac99c03c1

**Comment by dhemery** [comment]
Please update DHE-Modules to v1.0.3
Commit: e9f5670ec1c38f0df606943b093a200d0631d924

**Comment by dhemery** [comment]
If you haven’t already pulled the trigger on this, please hold off. I have a few adjustments to make.

**Comment by dhemery** [comment]
Please update DHE-Modules to v1.0.3
Commit: bbfeacc83163198e60aa390bd385a71af3585d07

**Comment by dhemery** [comment]
Please update DHE-Modules. I believe I have fixed the duplicate port issue in Fuzzy Logic H and Z, but I haven't built against the upcoming Rack with the new duplicate port assertions.

Version: 1.0.4
Commit: 6a2032ff1f0330ad1c25fd01f748b4dd255b57c2

**Comment by dhemery** [comment]
Please update DHE-Modules to v1.0.5
Commit: bdfa27954d5c30854d9df26ed122ba531080429a

**Comment by dhemery** [comment]
Please update DHE-Modules to v1.1.0
Commit: 98ffbe3553b98b90ed4d3b9d8a7ff4ac81bf4cb6

**Comment by dhemery** [comment]
Please update DHE-Modules to v1.1.1
Commit: 226c1a67bb5207b1fcb0b88c1fe4a793480a943e

My previous release inadvertently moved the Ranger module's controls to inadvisable places.

**Comment by dhemery** [comment]
Please update DHE-Modules to version 1.2.0.
Commit: 76590d4fa0f6522d5524a476b59c8de603d4b602

**Comment by dhemery** [comment]
Please update DHE-Modules to version 1.3.0.
Commit: e1e9b226601917cba0d21e792fc9f5e4e9baa022

**Comment by dhemery** [comment]
Please update DHE-Modules to version 1.4.0.
Commit: b5bea4d9cb07dc0802c2dc109ad5bb9b94cddc00

**Comment by dhemery** [comment]
Please update DHE-Modules to version 1.5.0.
Commit: 3abf4602f6e43e72dcde9982f2c7d23f21325d8a

**Comment by dhemery** [comment]
Please update DHE-Modules to version 1.5.1.
Commit: b5a6ff0bed29991c1407f4bddc5246ddb5281196

**Comment by dhemery** [comment]
Please update DHE-Modules to version 2.0.0.
Commit: 89274adf1d6df1e58b879cbd421ca9dbe35078bc

**Comment by dhemery** [comment]
Please update DHE-Modules to v2.0.1.
Commit: b43e0278dbbaa48915a820870f4dee4f1818aa56

**Comment by dhemery** [comment]
Please update DHE-Modules to v2.0.2
Commit: 08b7fc1115391f54fa68b245c2d11f35bc034150

Feel free to either publish or abandon v2.0.1, whichever is easier for you.

**Comment by dhemery** [comment]
I’m not sure if you noticed this, so I’ll post it again:

Please update DHE-Modules to v2.0.2
Commit: 08b7fc1115391f54fa68b245c2d11f35bc034150

**Comment by dhemery** [comment]
Please update DHE-Modules to v2.0.3
Commit: 1d1c286fc69babdb36dfe5fa4fe2856b0f707854
