### ISSUE TITLE
BaconMusic

### ISSUE THREAD

**Issue by baconpaul** [VCVRack/library#433]
This is the standing issue for BaconMusic plugin, so I can communicate with the Community team, per the README.

https://github.com/baconpaul/BaconPlugs

**Comment by baconpaul** [comment]
Hi folks!

I just release v0.6.1 of my module set, adding 3 new modules which implement the NES oscillator set and things like that. I also updated the documentation, added a contributor agreement, and did a bunch of little cleanups.

Per the readme:

* The new version is v0.6.1
* The transaction: b30dad642d8f57eed78d241a4251f96c1ec3319d
* The branch is release_v0.6.1

That transaction is the head transaction in GitHub now and as of this writing the branch and master are completely in sync.

I've built it on mac, but it should build on windows and linux too; just more straight forward C++. But if it doesn't please let me know and I can take a look at the error. 

And I really appreciate the community work here! Seeing my modules pop up in the 0.6 Rack release was super cool. Thanks for all you do!

**Comment by AndrewBelt** [comment]
`make dist`:

```
rm -rf dist
mkdir -p dist/BaconMusic
# Strip and copy plugin binary
cp plugin.dylib dist/BaconMusic/
x86_64-apple-darwin15-strip -S dist/BaconMusic/plugin.dylib
# Copy distributables
cp -R LICENSE.txt res doc patches README.md dist/BaconMusic/
cp: cannot stat 'doc': No such file or directory
make: *** [../../Rack-SDK/plugin.mk:52: dist] Error 1
make: Leaving directory '/home/vortico/src/cpp/VCV/public/community/repos/BaconMusic'
```

**Comment by baconpaul** [comment]
Oh shoot sorry. I renamed “doc” to “docs” in this release to follow a github recommendation.

I’ll name it back and repush the branch.

So sorry!

On Apr 4, 2018, at 17:33, Andrew Belt <notifications@github.com<mailto:notifications@github.com>> wrote:


make dist:

rm -rf dist
mkdir -p dist/BaconMusic
# Strip and copy plugin binary
cp plugin.dylib dist/BaconMusic/
x86_64-apple-darwin15-strip -S dist/BaconMusic/plugin.dylib
# Copy distributables
cp -R LICENSE.txt res doc patches README.md dist/BaconMusic/
cp: cannot stat 'doc': No such file or directory
make: *** [../../Rack-SDK/plugin.mk:52: dist] Error 1
make: Leaving directory '/home/vortico/src/cpp/VCV/public/community/repos/BaconMusic'

**Comment by baconpaul** [comment]
So sorry. Updated the makefile and pushed it all to GitHub. The new transaction id is 

6f235d1cff2b3d4cc8f334545ad36e8e0cbf1ccc

```
paul:~/dev/VCVRack/Rack/plugins/BaconPlugs$ git rev-parse HEAD
6f235d1cff2b3d4cc8f334545ad36e8e0cbf1ccc
paul:~/dev/VCVRack/Rack/plugins/BaconPlugs$ git diff -r b30dad642d8f57eed78d241a4251f96c1ec3319d Makefile
diff --git a/Makefile b/Makefile
index f8553c1..ed2df75 100644
--- a/Makefile
+++ b/Makefile
@@ -17,7 +17,7 @@ SOURCES += $(wildcard src/*.cpp)
 
 # Add files to the ZIP package when running `make dist`
 # The compiled plugin is automatically added.
-DISTRIBUTABLES += $(wildcard LICENSE*) res doc patches README.md
+DISTRIBUTABLES += $(wildcard LICENSE*) res docs patches README.md
 
 # Include the VCV plugin Makefile framework
 RACK_DIR ?= ../..
```

**Comment by phdsg** [comment]
looks like the repo-pointer and the manifest are up-to-date.
@AndrewBelt build issues with this?

**Comment by phdsg** [comment]
@baconpaul 
ok, quick build check on windows vs Rack-SDK.
guess this...
```
g++ -Werror -Wsuggest-override -std=c++11  -DSLUG=BaconMusic -fPIC -I/h/devel/vcv/Rack-SDK/include -I/h/devel/vcv/Rack-SDK/dep/include -DVERSION=0.6.1 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES -c -o build/src/ChipNoise.cpp.o src/ChipNoise.cpp
In file included from src/ChipNoise.cpp:2:0:
src/ChipSym.hpp:85:42: error: 'uint' has not been declared
     NESTriangle( float imin, float imax, uint sampleRate )
                                          ^~~~
src/ChipSym.hpp: In member function 'void ChipSym::NESTriangle::setWavelengthInSeconds(float)':
src/ChipSym.hpp:111:26: error: 'uint' was not declared in this scope
       setDigWavelength( (uint)( seconds * NESNTSCCPURate * 1000 * 1000 / 32 ) );
                          ^~~~
src/ChipSym.hpp:111:26: note: suggested alternative: 'rint'
       setDigWavelength( (uint)( seconds * NESNTSCCPURate * 1000 * 1000 / 32 ) );
                          ^~~~
                          rint
src/ChipSym.hpp: At global scope:
src/ChipSym.hpp:117:51: error: 'uint' has not been declared
     NESArbitraryWaveform( float imin, float imax, uint sampleRate ) : NESTriangle( imin, imax, sampleRate ) { }
                                                   ^~~~
src/ChipSym.hpp:119:28: error: 'uint' has not been declared
     void setWaveformPoint( uint pos,  // 0->31
                            ^~~~
src/ChipSym.hpp:120:28: error: 'uint' has not been declared
                            uint val ) // 0->15
                            ^~~~
src/ChipSym.hpp:125:5: error: 'uint' does not name a type; did you mean 'rint'?
     uint getWaveformPoint( uint pos ) { return waveForm[ pos ] * 15.0f; }
     ^~~~
     rint
src/ChipSym.hpp: In member function 'void ChipSym::NESPulse::setWavelengthInSeconds(float)':
src/ChipSym.hpp:180:26: error: 'uint' was not declared in this scope
       setDigWavelength( (uint)( seconds * NESNTSCCPURate * 1000 * 1000 / 2.0 / 8.0) );
                          ^~~~
src/ChipSym.hpp:180:26: note: suggested alternative: 'rint'
       setDigWavelength( (uint)( seconds * NESNTSCCPURate * 1000 * 1000 / 2.0 / 8.0) );
                          ^~~~
                          rint
src/ChipSym.hpp: At global scope:
src/ChipSym.hpp:228:21: error: 'uint' has not been declared
     void setPeriod( uint c ) // 0 - 15
                     ^~~~
src/ChipSym.hpp:290:18: error: 'bitset' in namespace 'std' does not name a template type
     typedef std::bitset< 24 > bits;
                  ^~~~~~
src/ChipSym.hpp:296:24: error: 'uint' has not been declared
     void setTapsAsInt( uint taps ) // so 1 << 16 & 1 << 14 & 1 << 7 type thing
                        ^~~~
src/ChipNoise.cpp: In member function 'virtual void ChipNoise::step()':
src/ChipNoise.cpp:46:5: error: 'uint' was not declared in this scope
     uint nl = clamp( params[ NOISE_LENGTH ].value, 0.0f, 15.0f );
     ^~~~
src/ChipNoise.cpp:46:5: note: suggested alternative: 'rint'
     uint nl = clamp( params[ NOISE_LENGTH ].value, 0.0f, 15.0f );
     ^~~~
     rint
src/ChipNoise.cpp:48:7: error: 'nl' was not declared in this scope
       nl = clamp( inputs[ NOISE_LENGTH_INPUT ].value * 1.5, 0.0f, 15.0f );
       ^~
src/ChipNoise.cpp:50:41: error: 'nl' was not declared in this scope
     lights[ NOISE_LENGTH_ONES ].value = nl % 10;
                                         ^~
make[1]: *** [/h/devel/vcv/Rack-SDK/compile.mk:62: build/src/ChipNoise.cpp.o] Error 1
make[1]: Leaving directory '/h/devel/vcv/community/repos/BaconMusic'
```
prevents a successful update.

**Comment by baconpaul** [comment]
Wow thanks! Uint isn’t a standard type. Huh.

I’ll change to size_t and what not and let you know

  - Paul

On Apr 12, 2018, at 16:13, phdsg vn chfhn <notifications@github.com<mailto:notifications@github.com>> wrote:


@baconpaul<https://github.com/baconpaul>
ok, quick build check on windows vs Rack-SDK.
guess this...

g++ -Werror -Wsuggest-override -std=c++11  -DSLUG=BaconMusic -fPIC -I/h/devel/vcv/Rack-SDK/include -I/h/devel/vcv/Rack-SDK/dep/include -DVERSION=0.6.1 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES -c -o build/src/ChipNoise.cpp.o src/ChipNoise.cpp
In file included from src/ChipNoise.cpp:2:0:
src/ChipSym.hpp:85:42: error: 'uint' has not been declared
     NESTriangle( float imin, float imax, uint sampleRate )
                                          ^~~~
src/ChipSym.hpp: In member function 'void ChipSym::NESTriangle::setWavelengthInSeconds(float)':
src/ChipSym.hpp:111:26: error: 'uint' was not declared in this scope
       setDigWavelength( (uint)( seconds * NESNTSCCPURate * 1000 * 1000 / 32 ) );
                          ^~~~
src/ChipSym.hpp:111:26: note: suggested alternative: 'rint'
       setDigWavelength( (uint)( seconds * NESNTSCCPURate * 1000 * 1000 / 32 ) );
                          ^~~~
                          rint
src/ChipSym.hpp: At global scope:
src/ChipSym.hpp:117:51: error: 'uint' has not been declared
     NESArbitraryWaveform( float imin, float imax, uint sampleRate ) : NESTriangle( imin, imax, sampleRate ) { }
                                                   ^~~~
src/ChipSym.hpp:119:28: error: 'uint' has not been declared
     void setWaveformPoint( uint pos,  // 0->31
                            ^~~~
src/ChipSym.hpp:120:28: error: 'uint' has not been declared
                            uint val ) // 0->15
                            ^~~~
src/ChipSym.hpp:125:5: error: 'uint' does not name a type; did you mean 'rint'?
     uint getWaveformPoint( uint pos ) { return waveForm[ pos ] * 15.0f; }
     ^~~~
     rint
src/ChipSym.hpp: In member function 'void ChipSym::NESPulse::setWavelengthInSeconds(float)':
src/ChipSym.hpp:180:26: error: 'uint' was not declared in this scope
       setDigWavelength( (uint)( seconds * NESNTSCCPURate * 1000 * 1000 / 2.0 / 8.0) );
                          ^~~~
src/ChipSym.hpp:180:26: note: suggested alternative: 'rint'
       setDigWavelength( (uint)( seconds * NESNTSCCPURate * 1000 * 1000 / 2.0 / 8.0) );
                          ^~~~
                          rint
src/ChipSym.hpp: At global scope:
src/ChipSym.hpp:228:21: error: 'uint' has not been declared
     void setPeriod( uint c ) // 0 - 15
                     ^~~~
src/ChipSym.hpp:290:18: error: 'bitset' in namespace 'std' does not name a template type
     typedef std::bitset< 24 > bits;
                  ^~~~~~
src/ChipSym.hpp:296:24: error: 'uint' has not been declared
     void setTapsAsInt( uint taps ) // so 1 << 16 & 1 << 14 & 1 << 7 type thing
                        ^~~~
src/ChipNoise.cpp: In member function 'virtual void ChipNoise::step()':
src/ChipNoise.cpp:46:5: error: 'uint' was not declared in this scope
     uint nl = clamp( params[ NOISE_LENGTH ].value, 0.0f, 15.0f );
     ^~~~
src/ChipNoise.cpp:46:5: note: suggested alternative: 'rint'
     uint nl = clamp( params[ NOISE_LENGTH ].value, 0.0f, 15.0f );
     ^~~~
     rint
src/ChipNoise.cpp:48:7: error: 'nl' was not declared in this scope
       nl = clamp( inputs[ NOISE_LENGTH_INPUT ].value * 1.5, 0.0f, 15.0f );
       ^~
src/ChipNoise.cpp:50:41: error: 'nl' was not declared in this scope
     lights[ NOISE_LENGTH_ONES ].value = nl % 10;
                                         ^~
make[1]: *** [/h/devel/vcv/Rack-SDK/compile.mk:62: build/src/ChipNoise.cpp.o] Error 1
make[1]: Leaving directory '/h/devel/vcv/community/repos/BaconMusic'


prevents a successful update.

**Comment by baconpaul** [comment]
Alright I replaced all my "uint" with "unsigned int" and it builds and works fine on my mac.

aba66e3469f2ade27cbb26d33efd9fd9395aaeec

on the revision branch

I'm working on 0.6.2 - will be a month or so. Before I ask for that I'll try and get a windows build environment running.

**Comment by mdemanett** [comment]
Checked the builds, reviewed, updated the pointer to the release_v0.6.1 branch: good to go.

**Comment by baconpaul** [comment]
Thanks! You guys rock. And sorry for the noise.

**Comment by phdsg** [comment]
updated build.

**Comment by baconpaul** [comment]
Hi.

Long time I know. I have a few small updates to my modules I would love to build. I can't seem to re-open this issue. Is posting here still the correct thing to do?

* Version: v0.6.3
* Transaction:  5a9ac2f7e66038f8a659a6cb48194312bec22c10
* Branch:  release_v0.6.3

Thank you.

**Comment by AndrewBelt** [comment]
Updated build

**Comment by baconpaul** [comment]
Hi @cschol I saw you asked on community for builds that work with 1.0

BaconMusic works with Rack v1 built this morning on the v1-gpl branch (rack hash fee87cddff040df43dee00cead77a401b19713ad) and seems to all work.

Here's the information you need.

* Version: v1.0.0
* Transaction:  c29ae0a9e6a0b4a75ce5fae3aca9a08606c0bd01
* Branch:  candidate_v1.0.0

I plan to add some polyphonic features to some of these modules, and also have another big set of modules I'm working on which are 1.0 ready in about 3-4 weeks I think, but for now, this would be a good thing to have in the plugin manager when you start doing builds.

Let me know if you experience any problems. And I have no particular rush. Just posting this since you asked on the v1 dev blog.

Thanks!

**Comment by cschol** [comment]
@baconpaul One thing I noticed: there are no module tags defined in the manifest `plugin.json`. Can you please add those? Also, please set the `manualUrl` to the `README.md` in the GitHub repo in lieu of any other official manual. Thank you!

**Comment by baconpaul** [comment]
Oh sure sorry. I’ll do that tomorrow and update this issue. Thanks!

**Comment by baconpaul** [comment]
Hi all.

I'd actually like to tick up the version of these plugins for the v1 release. I didn't think I would have time to get a bunch of V1 features in before you shipped Rack1 but it turns out I did. So I've actually done a pretty substantial update, including polyphony everywhere, new and better panels on everything, a new poly generator, and a couple of other cleanups and bug fixes.

So I would really like version 1.0.1 to be the one that we ship when rack 1 starts building plugins.

The details are all here. Let me know if you see any problems.

The one thing to note: BaconMusic now has a git submodule. So to build the code you need to do a `git submodule update --init --recursive` when you check it out. I had asked on the community board if there was a way to express that dependency in make, and Andrew told me there wasn't. If there's something I should change to make that easier for you let me know. (Since you set up community as a big submodule I presume you just do that submodule pull recursively at the outset anyway so we are fine, but I did want to mention it).

Thanks!


* Version: v1.0.1
* Transaction:  e6a5ab3972dcdf9040e19f964efbf8718897a856
* Branch:  release_v1.0.1

**Comment by cschol** [comment]
Can you please update the `license` field in the `plugin.json` to use a license designation from [SPDX](https://spdx.org/licenses/), e.g. `GPL-1.0-or-later` or `GPL-3.0-only`. Other than that it looks good. Thanks!

**Comment by baconpaul** [comment]
Thanks and no problem; updated above!

**Comment by AndrewBelt** [comment]
Could you remove the docs/ folder from DISTRIBUTABLES? The `manualUrl` points to the website, so there's no need to put documentation in the package. It just needlessly increases download times.
No need to bump the plugin version.

**Comment by baconpaul** [comment]
No problem at all! Here's the new commit point.

* Version: v1.0.1
* Transaction:  b155a4373e59a52902def1b3fb8793a19f7cbd9b
* Branch:  release_v1.0.1

**Comment by cschol** [comment]
Invalid tag in plugin.json: https://github.com/baconpaul/BaconPlugs/issues/29

**Comment by baconpaul** [comment]
Fixed at 73deeda8d0468a5700ab2a3e5edd7e9f891f2316

**Comment by baconpaul** [comment]
Heya folks. 

A user has found a bug in one of my modules that (1) causes a crash with the version from the plugin manager and (2) is entirely my fault. Basically when I reshuffled to do polyphony I initialized something out of order. The bad memory read works in my dev area but not in your build. Entirely my fault as I said.

So I have a fix - it's actually a really easy fix - but do I need to bump my version number since the plugin manager is live? That is: do I make a 1.0.2 or can I just do another revision for 1.0.1 and you update the build and everyone gets a fresh download? Let me know which you prefer!

Thank you

**Comment by AndrewBelt** [comment]
Yes, version bump is required.

**Comment by baconpaul** [comment]
Cool.

Here's my new version information. This fixes a SEGV in the KarplusStrongPoly module in the current v1.0.1 build when you drag a module out. (This was masked in my dev area).  The user who reported it confirms this version corrects it, as do i once I reproduced the problem.

Thank you very much!

* Version: v1.0.2
* Transaction:  ef4e9d544629f423da71a371cc2bcd4a88318812
* Branch:  release_v1.0.2

**Comment by baconpaul** [comment]
@cschol curious what I need to do to get my v2 branch into the library? Sorry to tag you but just want to figure out the steps thanks!

**Comment by cschol** [comment]
The process is the same. Submit your working `v2` plugins in this thread with the SHA.

**Comment by baconpaul** [comment]
OK!

Repo: https://github.com/baconpaul/BaconPlugs/
SHA: 8da390aed7eb1a529e64ff77ff4eb988c68350a3

I'll do surge-rack also

Out of curiosity, how are people handling V2 vs main-as-v1 branch across the code base?

**Comment by cschol** [comment]
Thanks. 

Branching is up to you. From the library perspective it does not matter, as we just need a valid SHA on any branch. We have branched library to a `v2` branch and keep track of `v2` modules that way. `v1` will remain active so you can continue to submit updates to `v1` of the library.

**Comment by baconpaul** [comment]
Been a while. Anyway here's a version 2.1.0

* Version: v2.1.0
* Transaction:  83e382072542762d5bb3c60ef051fb3f125a6379
* Branch:  main

Thank you

**Comment by baconpaul** [comment]
Oh shoot I pressed a wrong button and this closed.

**Comment by baconpaul** [comment]
So just re-opened it. Sorry about that.

**Comment by baconpaul** [comment]
Hi!

A new version with a couple of fixes and couple of new modules.

Thanks

* Version: v2.2.0
* Hash:  39235bcf1596455e20b34245a93baecc6e5ae378
* Branch:  releases/v2.2.0

**Comment by baconpaul** [comment]
Hi folks!

version 2.3.0
2f466801e8fb3fedb1385de0cb902115d1609484

Thanks as always!

**Comment by AndrewBelt** [comment]
This plugin builds with Rack SDK 2.4.0 for Mac ARM64, but it doesn't load due to not finding the `init()` symbol. I'm not sure why that would be, but it could be an easy fix.

**Comment by baconpaul** [comment]
Thanks., I’m sure it’s the same thing as airwin. I run both with 23 on arm regularly so I’m sure it is easy indeed!

**Comment by baconpaul** [comment]
OK same fix as airwin2rack. thanks for flagging it

version 2.3.1
hash e3c5290cd7b4d0c4568fe32419294af81762a4ce

**Comment by baconpaul** [comment]
Morning friends!

v2.4.0
89ba1d6122e244c971e461716a731aefbed73d6e

adds support for the dark panel api consistently! Fixes a tiny bug or two also.

**Comment by baconpaul** [comment]
Hi Friends!

v2.5.0
Hash: 67cc7d4a7132ed906b4c72ec2ea41340bf2fd13e

thanks!

**Comment by baconpaul** [comment]
Hiya Folks

2.6.0
3e29a3f485cff78b005006d157058b292250d955

Finally added proper support for the dark panel api, and a few new tweaks and bits and bobs

Thanks as always

**Comment by baconpaul** [comment]
Hiya!

2.7.0
2886a282a0f8518e0515b549e426428db332378c

thanks!

**Comment by baconpaul** [comment]
Team 

no action required now but I have @cosinekitty write access to this repo and we had a chat about him being able to update it if I’m not around to so just letting you know either he or I could send you a version request in the future - thanks!
