### ISSUE TITLE
KarateSnoopy

### ISSUE THREAD

**Issue by KarateSnoopy** [VCVRack/library#506]
Hey, can you add my repo to the community repo as a submodule and hook it up the build magic?  
https://github.com/KarateSnoopy/vcv-karatesnoopy/

Here's the commit hash to use for my plugin's v0.6.1 which works with v0.6 of VCV Rack:
`c2b628e2638595852c8e7b566157a299f0c04c8a`

Here's the updated manifest:

```
{
  "name": "KarateSnoopy",
  "author": "KarateSnoopy",
  "license": "MIT",
  "manualUrl": "https://github.com/KarateSnoopy/vcv-karatesnoopy/blob/master/README.md",
  "sourceUrl": "https://github.com/KarateSnoopy/vcv-karatesnoopy",
  "latestVersion": "0.6.1",
  "status": "available"
}
```

Let me know if you need anything else.  Thanks!

**Comment by cschol** [comment]
This does not compile with the `Rack SDK`:

```
In file included from src/SEQWidget.cpp:5:0:
src/SeqModule.h:7:10: fatal error: SEQModule.h: No such file or directory
 #include "SEQModule.h"
          ^~~~~~~~~~~~~
compilation terminated.
/home/cschol/src/Rack/compile.mk:64: recipe for target 'build/src/SEQWidget.cpp.o' failed
make: *** [build/src/SEQWidget.cpp.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from src/SeqModule.cpp:1:0:
src/SeqModule.h:7:10: fatal error: SEQModule.h: No such file or directory
 #include "SEQModule.h"
          ^~~~~~~~~~~~~
compilation terminated.
/home/cschol/src/Rack/compile.mk:64: recipe for target 'build/src/SeqModule.cpp.o' failed
make: *** [build/src/SeqModule.cpp.o] Error 1
src/PluginInit.cpp:2:10: fatal error: SeqWidget.h: No such file or directory
 #include "SeqWidget.h"
          ^~~~~~~~~~~~~
compilation terminated.
/home/cschol/src/Rack/compile.mk:64: recipe for target 'build/src/PluginInit.cpp.o' failed
make: *** [build/src/PluginInit.cpp.o] Error 1
```

**Comment by KarateSnoopy** [comment]
Hmm, how do I reproduce this build error?  
I downloaded the rack sdk and it seems to build fine.  
The header SeqModule.h that src/SEQWidget.cpp is looking for is right next to the cpp file so it should find it as you can see here: https://github.com/KarateSnoopy/vcv-karatesnoopy/tree/master/src

Here's my build log:

Jason@jasonsa-home1 MINGW64 /f/git/KarateSnoopy
$ git clean -x -f -d

Jason@jasonsa-home1 MINGW64 /f/git/KarateSnoopy
$ git reset --hard origin/master
HEAD is now at c2b628e Fixing build

Jason@jasonsa-home1 MINGW64 /f/git/KarateSnoopy
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working tree clean

Jason@jasonsa-home1 MINGW64 /f/git/KarateSnoopy
$ RACK_DIR=/f/git/Rack-SDK/ make dist
g++  -Wsuggest-override -std=c++11  -DSLUG=KarateSnoopy -fPIC -I/f/git/Rack-SDK//include -I/f/git/Rack-SDK//dep/include -DVERSION=0.6.1 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES -c -o build/src/ButtonWithLight.cpp.o src/ButtonWithLight.cpp
g++  -Wsuggest-override -std=c++11  -DSLUG=KarateSnoopy -fPIC -I/f/git/Rack-SDK//include -I/f/git/Rack-SDK//dep/include -DVERSION=0.6.1 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES -c -o build/src/PluginInit.cpp.o src/PluginInit.cpp
g++  -Wsuggest-override -std=c++11  -DSLUG=KarateSnoopy -fPIC -I/f/git/Rack-SDK//include -I/f/git/Rack-SDK//dep/include -DVERSION=0.6.1 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES -c -o build/src/LCDNumberWidget.cpp.o src/LCDNumberWidget.cpp
g++  -Wsuggest-override -std=c++11  -DSLUG=KarateSnoopy -fPIC -I/f/git/Rack-SDK//include -I/f/git/Rack-SDK//dep/include -DVERSION=0.6.1 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES -c -o build/src/SeqModule.cpp.o src/SeqModule.cpp
src/SeqModule.cpp: In member function 'void SEQModule::InitUI(rack::ModuleWidget*, rack::Rect)':
src/SeqModule.cpp:49:116: warning: 'TParamWidget* rack::createParam(rack::Vec, rack::Module*, int, float, float, float) [with TParamWidget = Davies1900hSmallBlackKnob]' is deprecated [-Wdeprecated-declarations]
     addParam(createParam<Davies1900hSmallBlackKnob>(Vec(18 + 3, 56), module, SEQModule::CLOCK_PARAM, -2.0, 6.0, 2.0));
                                                                                                                    ^
In file included from src/ButtonWithLight.h:3:0,
                 from src/SeqModule.h:2,
                 from src/SeqModule.cpp:1:
F:/git/Rack-SDK/include/rack.hpp:49:26: note: declared here
 DEPRECATED TParamWidget *createParam(Vec pos, Module *module, int paramId, float minValue, float maxValue, float defaultValue) {
                          ^~~~~~~~~~~
src/SeqModule.cpp:50:120: warning: 'TParamWidget* rack::createParam(rack::Vec, rack::Module*, int, float, float, float) [with TParamWidget = Davies1900hSmallBlackKnob]' is deprecated [-Wdeprecated-declarations]
     addParam(createParam<Davies1900hSmallBlackKnob>(Vec(132 + 3, 56), module, SEQModule::STEPS_PARAM, 0.0, 10.0f, 10.0f));
                                                                                                                        ^
In file included from src/ButtonWithLight.h:3:0,
                 from src/SeqModule.h:2,
                 from src/SeqModule.cpp:1:
F:/git/Rack-SDK/include/rack.hpp:49:26: note: declared here
 DEPRECATED TParamWidget *createParam(Vec pos, Module *module, int paramId, float minValue, float maxValue, float defaultValue) {
                          ^~~~~~~~~~~
src/SeqModule.cpp:52:85: warning: 'TModuleLightWidget* rack::createLight(rack::Vec, rack::Module*, int) [with TModuleLightWidget = rack::SmallLight<rack::GreenLight>]' is deprecated [-Wdeprecated-declarations]
     addChild(createLight<SmallLight<GreenLight>>(Vec(180, y2 + 10), module, CV_LIGHT));
                                                                                     ^
In file included from src/ButtonWithLight.h:3:0,
                 from src/SeqModule.h:2,
                 from src/SeqModule.cpp:1:
F:/git/Rack-SDK/include/rack.hpp:83:32: note: declared here
 DEPRECATED TModuleLightWidget *createLight(Vec pos, Module *module, int firstLightId) {
                                ^~~~~~~~~~~
src/SeqModule.cpp:54:89: warning: 'TModuleLightWidget* rack::createLight(rack::Vec, rack::Module*, int) [with TModuleLightWidget = rack::SmallLight<rack::GreenLight>]' is deprecated [-Wdeprecated-declarations]
     addChild(createLight<SmallLight<GreenLight>>(Vec(219, y2 + 10), module, GATE_X_LIGHT));
                                                                                         ^
In file included from src/ButtonWithLight.h:3:0,
                 from src/SeqModule.h:2,
                 from src/SeqModule.cpp:1:
F:/git/Rack-SDK/include/rack.hpp:83:32: note: declared here
 DEPRECATED TModuleLightWidget *createLight(Vec pos, Module *module, int firstLightId) {
                                ^~~~~~~~~~~
src/SeqModule.cpp:56:89: warning: 'TModuleLightWidget* rack::createLight(rack::Vec, rack::Module*, int) [with TModuleLightWidget = rack::SmallLight<rack::GreenLight>]' is deprecated [-Wdeprecated-declarations]
     addChild(createLight<SmallLight<GreenLight>>(Vec(257, y2 + 10), module, GATE_Y_LIGHT));
                                                                                         ^
In file included from src/ButtonWithLight.h:3:0,
                 from src/SeqModule.h:2,
                 from src/SeqModule.cpp:1:
F:/git/Rack-SDK/include/rack.hpp:83:32: note: declared here
 DEPRECATED TModuleLightWidget *createLight(Vec pos, Module *module, int firstLightId) {
                                ^~~~~~~~~~~
src/SeqModule.cpp:58:103: warning: 'TModuleLightWidget* rack::createLight(rack::Vec, rack::Module*, int) [with TModuleLightWidget = rack::SmallLight<rack::GreenLight>]' is deprecated [-Wdeprecated-declarations]
     addChild(createLight<SmallLight<GreenLight>>(Vec(257 + 38 - 2, y2 + 10), module, GATE_X_OR_Y_LIGHT));
                                                                                                       ^
In file included from src/ButtonWithLight.h:3:0,
                 from src/SeqModule.h:2,
                 from src/SeqModule.cpp:1:
F:/git/Rack-SDK/include/rack.hpp:83:32: note: declared here
 DEPRECATED TModuleLightWidget *createLight(Vec pos, Module *module, int firstLightId) {
                                ^~~~~~~~~~~
src/SeqModule.cpp:81:91: warning: 'TPort* rack::createInput(rack::Vec, rack::Module*, int) [with TPort = rack::PJ301MPort]' is deprecated [-Wdeprecated-declarations]
     addInput(createInput<PJ301MPort>(Vec(portX[0] - 1, 98), module, SEQModule::CLOCK_INPUT));
                                                                                           ^
In file included from src/ButtonWithLight.h:3:0,
                 from src/SeqModule.h:2,
                 from src/SeqModule.cpp:1:
F:/git/Rack-SDK/include/rack.hpp:61:19: note: declared here
 DEPRECATED TPort *createInput(Vec pos, Module *module, int inputId) {
                   ^~~~~~~~~~~
src/SeqModule.cpp:82:95: warning: 'TPort* rack::createInput(rack::Vec, rack::Module*, int) [with TPort = rack::PJ301MPort]' is deprecated [-Wdeprecated-declarations]
     addInput(createInput<PJ301MPort>(Vec(portX[1] - 1, 98), module, SEQModule::EXT_CLOCK_INPUT));
                                                                                               ^
In file included from src/ButtonWithLight.h:3:0,
                 from src/SeqModule.h:2,
                 from src/SeqModule.cpp:1:
F:/git/Rack-SDK/include/rack.hpp:61:19: note: declared here
 DEPRECATED TPort *createInput(Vec pos, Module *module, int inputId) {
                   ^~~~~~~~~~~
src/SeqModule.cpp:83:91: warning: 'TPort* rack::createInput(rack::Vec, rack::Module*, int) [with TPort = rack::PJ301MPort]' is deprecated [-Wdeprecated-declarations]
     addInput(createInput<PJ301MPort>(Vec(portX[2] - 1, 98), module, SEQModule::RESET_INPUT));
                                                                                           ^
In file included from src/ButtonWithLight.h:3:0,
                 from src/SeqModule.h:2,
                 from src/SeqModule.cpp:1:
F:/git/Rack-SDK/include/rack.hpp:61:19: note: declared here
 DEPRECATED TPort *createInput(Vec pos, Module *module, int inputId) {
                   ^~~~~~~~~~~
src/SeqModule.cpp:84:91: warning: 'TPort* rack::createInput(rack::Vec, rack::Module*, int) [with TPort = rack::PJ301MPort]' is deprecated [-Wdeprecated-declarations]
     addInput(createInput<PJ301MPort>(Vec(portX[3] - 1, 98), module, SEQModule::STEPS_INPUT));
                                                                                           ^
In file included from src/ButtonWithLight.h:3:0,
                 from src/SeqModule.h:2,
                 from src/SeqModule.cpp:1:
F:/git/Rack-SDK/include/rack.hpp:61:19: note: declared here
 DEPRECATED TPort *createInput(Vec pos, Module *module, int inputId) {
                   ^~~~~~~~~~~
src/SeqModule.cpp:86:91: warning: 'TPort* rack::createOutput(rack::Vec, rack::Module*, int) [with TPort = rack::PJ301MPort]' is deprecated [-Wdeprecated-declarations]
     addOutput(createOutput<PJ301MPort>(Vec(portX[4] - 1, 98), module, SEQModule::CV_OUTPUT));
                                                                                           ^
In file included from src/ButtonWithLight.h:3:0,
                 from src/SeqModule.h:2,
                 from src/SeqModule.cpp:1:
F:/git/Rack-SDK/include/rack.hpp:72:19: note: declared here
 DEPRECATED TPort *createOutput(Vec pos, Module *module, int outputId) {
                   ^~~~~~~~~~~~
src/SeqModule.cpp:87:95: warning: 'TPort* rack::createOutput(rack::Vec, rack::Module*, int) [with TPort = rack::PJ301MPort]' is deprecated [-Wdeprecated-declarations]
     addOutput(createOutput<PJ301MPort>(Vec(portX[5] - 1, 98), module, SEQModule::GATE_X_OUTPUT));
                                                                                               ^
In file included from src/ButtonWithLight.h:3:0,
                 from src/SeqModule.h:2,
                 from src/SeqModule.cpp:1:
F:/git/Rack-SDK/include/rack.hpp:72:19: note: declared here
 DEPRECATED TPort *createOutput(Vec pos, Module *module, int outputId) {
                   ^~~~~~~~~~~~
src/SeqModule.cpp:88:95: warning: 'TPort* rack::createOutput(rack::Vec, rack::Module*, int) [with TPort = rack::PJ301MPort]' is deprecated [-Wdeprecated-declarations]
     addOutput(createOutput<PJ301MPort>(Vec(portX[6] - 1, 98), module, SEQModule::GATE_Y_OUTPUT));
                                                                                               ^
In file included from src/ButtonWithLight.h:3:0,
                 from src/SeqModule.h:2,
                 from src/SeqModule.cpp:1:
F:/git/Rack-SDK/include/rack.hpp:72:19: note: declared here
 DEPRECATED TPort *createOutput(Vec pos, Module *module, int outputId) {
                   ^~~~~~~~~~~~
src/SeqModule.cpp:89:98: warning: 'TPort* rack::createOutput(rack::Vec, rack::Module*, int) [with TPort = rack::PJ301MPort]' is deprecated [-Wdeprecated-declarations]
     addOutput(createOutput<PJ301MPort>(Vec(portX[7] - 1, 98), module, SEQModule::GATE_XORY_OUTPUT));
                                                                                                  ^
In file included from src/ButtonWithLight.h:3:0,
                 from src/SeqModule.h:2,
                 from src/SeqModule.cpp:1:
F:/git/Rack-SDK/include/rack.hpp:72:19: note: declared here
 DEPRECATED TPort *createOutput(Vec pos, Module *module, int outputId) {
                   ^~~~~~~~~~~~
src/SeqModule.cpp:101:120: warning: 'TParamWidget* rack::createParam(rack::Vec, rack::Module*, int, float, float, float) [with TParamWidget = rack::RoundBlackKnob]' is deprecated [-Wdeprecated-declarations]
             auto p = addParam(createParam<RoundBlackKnob>(Vec(x, y), module, SEQModule::PITCH_PARAM + iZ, 0.0, 6.0, 0.0));
                                                                                                                        ^
In file included from src/ButtonWithLight.h:3:0,
                 from src/SeqModule.h:2,
                 from src/SeqModule.cpp:1:
F:/git/Rack-SDK/include/rack.hpp:49:26: note: declared here
 DEPRECATED TParamWidget *createParam(Vec pos, Module *module, int paramId, float minValue, float maxValue, float defaultValue) {
                          ^~~~~~~~~~~
src/SeqModule.cpp:105:128: warning: 'TModuleLightWidget* rack::createLight(rack::Vec, rack::Module*, int) [with TModuleLightWidget = rack::SmallLight<rack::GreenLight>]' is deprecated [-Wdeprecated-declarations]
             m_editPitchUI.push_back(addChild(createLight<SmallLight<GreenLight>>(Vec(x + 12, y + 12), module, GATE_LIGHT_0 + iZ)));
                                                                                                                                ^
In file included from src/ButtonWithLight.h:3:0,
                 from src/SeqModule.h:2,
                 from src/SeqModule.cpp:1:
F:/git/Rack-SDK/include/rack.hpp:83:32: note: declared here
 DEPRECATED TModuleLightWidget *createLight(Vec pos, Module *module, int firstLightId) {
                                ^~~~~~~~~~~
src/SeqModule.cpp:147:137: warning: 'TParamWidget* rack::createParam(rack::Vec, rack::Module*, int, float, float, float) [with TParamWidget = Davies1900hSmallBlackSnapKnob]' is deprecated [-Wdeprecated-declarations]
     addParam(createParam<Davies1900hSmallBlackSnapKnob>(Vec(patternX, patternY + 40), module, SEQModule::PATTERN_PARAM, 0.0, 10.0f, 0.0f));
                                                                                                                                         ^
In file included from src/ButtonWithLight.h:3:0,
                 from src/SeqModule.h:2,
                 from src/SeqModule.cpp:1:
F:/git/Rack-SDK/include/rack.hpp:49:26: note: declared here
 DEPRECATED TParamWidget *createParam(Vec pos, Module *module, int paramId, float minValue, float maxValue, float defaultValue) {
                          ^~~~~~~~~~~
src/SeqModule.cpp:148:100: warning: 'TPort* rack::createInput(rack::Vec, rack::Module*, int) [with TPort = rack::PJ301MPort]' is deprecated [-Wdeprecated-declarations]
     addInput(createInput<PJ301MPort>(Vec(patternX, patternY + 70), module, SEQModule::PATTERN_INPUT));
                                                                                                    ^
In file included from src/ButtonWithLight.h:3:0,
                 from src/SeqModule.h:2,
                 from src/SeqModule.cpp:1:
F:/git/Rack-SDK/include/rack.hpp:61:19: note: declared here
 DEPRECATED TPort *createInput(Vec pos, Module *module, int inputId) {
                   ^~~~~~~~~~~
g++  -Wsuggest-override -std=c++11  -DSLUG=KarateSnoopy -fPIC -I/f/git/Rack-SDK//include -I/f/git/Rack-SDK//dep/include -DVERSION=0.6.1 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES -c -o build/src/TextLabelWidget.cpp.o src/TextLabelWidget.cpp
g++  -Wsuggest-override -std=c++11  -DSLUG=KarateSnoopy -fPIC -I/f/git/Rack-SDK//include -I/f/git/Rack-SDK//dep/include -DVERSION=0.6.1 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES -c -o build/src/utils.cpp.o src/utils.cpp
g++  -Wsuggest-override -std=c++11  -DSLUG=KarateSnoopy -fPIC -I/f/git/Rack-SDK//include -I/f/git/Rack-SDK//dep/include -DVERSION=0.6.1 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES -c -o build/src/SEQWidget.cpp.o src/SEQWidget.cpp
g++ -o plugin.dll build/src/ButtonWithLight.cpp.o build/src/PluginInit.cpp.o build/src/LCDNumberWidget.cpp.o build/src/SeqModule.cpp.o build/src/TextLabelWidget.cpp.o build/src/utils.cpp.o build/src/SEQWidget.cpp.o  -shared -L/f/git/Rack-SDK/ -lRack
rm -rf dist
mkdir -p dist/KarateSnoopy
# Strip and copy plugin binary
cp plugin.dll dist/KarateSnoopy/
strip -s dist/KarateSnoopy/plugin.dll
# Copy distributables
cp -R LICENSE res dist/KarateSnoopy/
# Create ZIP package
cd dist && zip -5 -r KarateSnoopy-0.6.1-win.zip KarateSnoopy
  adding: KarateSnoopy/ (stored 0%)
  adding: KarateSnoopy/LICENSE (deflated 41%)
  adding: KarateSnoopy/plugin.dll (deflated 70%)
  adding: KarateSnoopy/res/ (stored 0%)
  adding: KarateSnoopy/res/Davies1900hSmallBlack.svg (deflated 67%)
  adding: KarateSnoopy/res/OFL License - Segment7Standard.txt (deflated 56%)
  adding: KarateSnoopy/res/Roboto LICENSE.txt (deflated 65%)
  adding: KarateSnoopy/res/Roboto-Black.ttf (deflated 46%)
  adding: KarateSnoopy/res/Segment7Standard.ttf (deflated 75%)
  adding: KarateSnoopy/res/SeqModule.svg (deflated 78%)

**Comment by KarateSnoopy** [comment]
@cschol should https://github.com/VCVRack/community/blob/master/manifests/KarateSnoopy.json#L8 be "0.6.1"?

**Comment by cschol** [comment]
No. That version will be updated when Andrew builds the module successfully and it is available in the plugin manager. I did the staging, now it will usually take a few days to get incorporated.

**Comment by AndrewBelt** [comment]
Updated build

**Comment by KarateSnoopy** [comment]
@cschol Hey, I ported the KarateSnoopy plugin to v1 at https://github.com/KarateSnoopy/vcv-karatesnoopy/tree/v1.  Can you track it at https://github.com/VCVRack/library/projects/1?

Thanks!

**Comment by cschol** [comment]
plugin.json and slug need update: https://github.com/KarateSnoopy/vcv-karatesnoopy/issues/9

**Comment by KarateSnoopy** [comment]
Thanks @cschol  
Fixed.  Can you take look again?
